import { LightThemeContextProvider } from '../contexts/LightThemeContext'
import { Poppins } from 'next/font/google'
import type { ReactNode } from 'react'
import type { Metadata } from 'next'
import '../styles/global.scss'

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <LightThemeContextProvider>
      <html lang="en">
        <body className={poppins.className}>{children}</body>
      </html>
    </LightThemeContextProvider>
  )
}
